[package]
name = "scribe-notes"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
scribe-common = { version = "0.1.0", path = "../scribe-common" }
tera = "1.20.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
